// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDisplayname holds the string denoting the displayname field in the database.
	FieldDisplayname = "displayname"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// FieldLoginFrequency holds the string denoting the login_frequency field in the database.
	FieldLoginFrequency = "login_frequency"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// FieldAPIToken holds the string denoting the api_token field in the database.
	FieldAPIToken = "api_token"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldAuthType holds the string denoting the auth_type field in the database.
	FieldAuthType = "auth_type"
	// FieldOnlyOss holds the string denoting the only_oss field in the database.
	FieldOnlyOss = "only_oss"
	// Table holds the table name of the user in the database.
	Table = "user"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDisplayname,
	FieldPassword,
	FieldEmail,
	FieldPhone,
	FieldLoginFrequency,
	FieldActive,
	FieldAPIToken,
	FieldRole,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldAuthType,
	FieldOnlyOss,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultActive holds the default value on creation for the "active" field.
	DefaultActive int8
	// DefaultRole holds the default value on creation for the "role" field.
	DefaultRole int32
	// DefaultOnlyOss holds the default value on creation for the "only_oss" field.
	DefaultOnlyOss int8
)
